name: YESTODAY CI

on:
  pull_request:
    branches:
      - main
      - 'v*.[0-9]'

jobs:
  test:
    name: Run tests and format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['22.3']
        elixir: ['1.13']
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{matrix.otp}}
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Run Tests
        run: mix test